// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.17.0
// source: twopc.proto

package twopc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Twopc_ClientRequest_FullMethodName                      = "/twopc.twopc/ClientRequest"
	Twopc_ClientReadRequest_FullMethodName                  = "/twopc.twopc/ClientReadRequest"
	Twopc_IntershardParticipantClientRequest_FullMethodName = "/twopc.twopc/IntershardParticipantClientRequest"
	Twopc_PrepareRequest_FullMethodName                     = "/twopc.twopc/PrepareRequest"
	Twopc_AcceptRequest_FullMethodName                      = "/twopc.twopc/AcceptRequest"
	Twopc_TwoPCAcceptRequest_FullMethodName                 = "/twopc.twopc/TwoPCAcceptRequest"
	Twopc_Commit_FullMethodName                             = "/twopc.twopc/Commit"
	Twopc_TwoPCPaxosAbortCommit_FullMethodName              = "/twopc.twopc/TwoPCPaxosAbortCommit"
	Twopc_NewViewRequest_FullMethodName                     = "/twopc.twopc/NewViewRequest"
	Twopc_NewViewUpdate_FullMethodName                      = "/twopc.twopc/NewViewUpdate"
	Twopc_UpdateAvailability_FullMethodName                 = "/twopc.twopc/UpdateAvailability"
	Twopc_PrintDB_FullMethodName                            = "/twopc.twopc/PrintDB"
	Twopc_PrintLogs_FullMethodName                          = "/twopc.twopc/PrintLogs"
	Twopc_PrintBalance_FullMethodName                       = "/twopc.twopc/PrintBalance"
	Twopc_Flush_FullMethodName                              = "/twopc.twopc/Flush"
	Twopc_GetCurrentLeader_FullMethodName                   = "/twopc.twopc/GetCurrentLeader"
	Twopc_TwoPCClientRequest_FullMethodName                 = "/twopc.twopc/TwoPCClientRequest"
	Twopc_TwoPCPrepare_FullMethodName                       = "/twopc.twopc/TwoPCPrepare"
	Twopc_TwoPCAbort_FullMethodName                         = "/twopc.twopc/TwoPCAbort"
	Twopc_TwoPCCommit_FullMethodName                        = "/twopc.twopc/TwoPCCommit"
	Twopc_UpdateClients_FullMethodName                      = "/twopc.twopc/UpdateClients"
)

// TwopcClient is the client API for Twopc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwopcClient interface {
	ClientRequest(ctx context.Context, in *ClientReq, opts ...grpc.CallOption) (*ClientResp, error)
	ClientReadRequest(ctx context.Context, in *ClientReadReq, opts ...grpc.CallOption) (*ClientReadResp, error)
	IntershardParticipantClientRequest(ctx context.Context, in *ClientReq, opts ...grpc.CallOption) (*ClientResp, error)
	PrepareRequest(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PromiseAck, error)
	AcceptRequest(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*Accepted, error)
	TwoPCAcceptRequest(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*Accepted, error)
	Commit(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*Empty, error)
	TwoPCPaxosAbortCommit(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*Empty, error)
	NewViewRequest(ctx context.Context, in *NewViewReq, opts ...grpc.CallOption) (*NewView, error)
	NewViewUpdate(ctx context.Context, in *Ballot, opts ...grpc.CallOption) (*Empty, error)
	UpdateAvailability(ctx context.Context, in *IsAvailable, opts ...grpc.CallOption) (*IsAvailable, error)
	PrintDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllBalance, error)
	PrintLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllLogs, error)
	PrintBalance(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*Balance, error)
	Flush(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetCurrentLeader(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ballot, error)
	// ⟨REQUEST,t,τ,c⟩
	TwoPCClientRequest(ctx context.Context, in *ClientReq, opts ...grpc.CallOption) (*ClientResp, error)
	// ⟨PREPARE,t,m⟩ // ⟨PREPARED,t,m⟩
	TwoPCPrepare(ctx context.Context, in *TwoPCMessage, opts ...grpc.CallOption) (*Prepared, error)
	// ⟨ABORT,t,m⟩
	TwoPCAbort(ctx context.Context, in *TwoPCMessage, opts ...grpc.CallOption) (*Ack, error)
	// ⟨COMMIT,t,m⟩
	TwoPCCommit(ctx context.Context, in *TwoPCMessage, opts ...grpc.CallOption) (*Ack, error)
	UpdateClients(ctx context.Context, in *TwoPCMessage, opts ...grpc.CallOption) (*Ack, error)
}

type twopcClient struct {
	cc grpc.ClientConnInterface
}

func NewTwopcClient(cc grpc.ClientConnInterface) TwopcClient {
	return &twopcClient{cc}
}

func (c *twopcClient) ClientRequest(ctx context.Context, in *ClientReq, opts ...grpc.CallOption) (*ClientResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResp)
	err := c.cc.Invoke(ctx, Twopc_ClientRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) ClientReadRequest(ctx context.Context, in *ClientReadReq, opts ...grpc.CallOption) (*ClientReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientReadResp)
	err := c.cc.Invoke(ctx, Twopc_ClientReadRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) IntershardParticipantClientRequest(ctx context.Context, in *ClientReq, opts ...grpc.CallOption) (*ClientResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResp)
	err := c.cc.Invoke(ctx, Twopc_IntershardParticipantClientRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) PrepareRequest(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PromiseAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromiseAck)
	err := c.cc.Invoke(ctx, Twopc_PrepareRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) AcceptRequest(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*Accepted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Accepted)
	err := c.cc.Invoke(ctx, Twopc_AcceptRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) TwoPCAcceptRequest(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*Accepted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Accepted)
	err := c.cc.Invoke(ctx, Twopc_TwoPCAcceptRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) Commit(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Twopc_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) TwoPCPaxosAbortCommit(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Twopc_TwoPCPaxosAbortCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) NewViewRequest(ctx context.Context, in *NewViewReq, opts ...grpc.CallOption) (*NewView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewView)
	err := c.cc.Invoke(ctx, Twopc_NewViewRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) NewViewUpdate(ctx context.Context, in *Ballot, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Twopc_NewViewUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) UpdateAvailability(ctx context.Context, in *IsAvailable, opts ...grpc.CallOption) (*IsAvailable, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAvailable)
	err := c.cc.Invoke(ctx, Twopc_UpdateAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) PrintDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllBalance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllBalance)
	err := c.cc.Invoke(ctx, Twopc_PrintDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) PrintLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllLogs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllLogs)
	err := c.cc.Invoke(ctx, Twopc_PrintLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) PrintBalance(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*Balance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Balance)
	err := c.cc.Invoke(ctx, Twopc_PrintBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) Flush(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Twopc_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) GetCurrentLeader(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ballot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ballot)
	err := c.cc.Invoke(ctx, Twopc_GetCurrentLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) TwoPCClientRequest(ctx context.Context, in *ClientReq, opts ...grpc.CallOption) (*ClientResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResp)
	err := c.cc.Invoke(ctx, Twopc_TwoPCClientRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) TwoPCPrepare(ctx context.Context, in *TwoPCMessage, opts ...grpc.CallOption) (*Prepared, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prepared)
	err := c.cc.Invoke(ctx, Twopc_TwoPCPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) TwoPCAbort(ctx context.Context, in *TwoPCMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Twopc_TwoPCAbort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) TwoPCCommit(ctx context.Context, in *TwoPCMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Twopc_TwoPCCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twopcClient) UpdateClients(ctx context.Context, in *TwoPCMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Twopc_UpdateClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwopcServer is the server API for Twopc service.
// All implementations must embed UnimplementedTwopcServer
// for forward compatibility.
type TwopcServer interface {
	ClientRequest(context.Context, *ClientReq) (*ClientResp, error)
	ClientReadRequest(context.Context, *ClientReadReq) (*ClientReadResp, error)
	IntershardParticipantClientRequest(context.Context, *ClientReq) (*ClientResp, error)
	PrepareRequest(context.Context, *PrepareReq) (*PromiseAck, error)
	AcceptRequest(context.Context, *Accept) (*Accepted, error)
	TwoPCAcceptRequest(context.Context, *Accept) (*Accepted, error)
	Commit(context.Context, *CommitMessage) (*Empty, error)
	TwoPCPaxosAbortCommit(context.Context, *CommitMessage) (*Empty, error)
	NewViewRequest(context.Context, *NewViewReq) (*NewView, error)
	NewViewUpdate(context.Context, *Ballot) (*Empty, error)
	UpdateAvailability(context.Context, *IsAvailable) (*IsAvailable, error)
	PrintDB(context.Context, *Empty) (*AllBalance, error)
	PrintLogs(context.Context, *Empty) (*AllLogs, error)
	PrintBalance(context.Context, *ClientID) (*Balance, error)
	Flush(context.Context, *Empty) (*Empty, error)
	GetCurrentLeader(context.Context, *Empty) (*Ballot, error)
	// ⟨REQUEST,t,τ,c⟩
	TwoPCClientRequest(context.Context, *ClientReq) (*ClientResp, error)
	// ⟨PREPARE,t,m⟩ // ⟨PREPARED,t,m⟩
	TwoPCPrepare(context.Context, *TwoPCMessage) (*Prepared, error)
	// ⟨ABORT,t,m⟩
	TwoPCAbort(context.Context, *TwoPCMessage) (*Ack, error)
	// ⟨COMMIT,t,m⟩
	TwoPCCommit(context.Context, *TwoPCMessage) (*Ack, error)
	UpdateClients(context.Context, *TwoPCMessage) (*Ack, error)
	mustEmbedUnimplementedTwopcServer()
}

// UnimplementedTwopcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwopcServer struct{}

func (UnimplementedTwopcServer) ClientRequest(context.Context, *ClientReq) (*ClientResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientRequest not implemented")
}
func (UnimplementedTwopcServer) ClientReadRequest(context.Context, *ClientReadReq) (*ClientReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientReadRequest not implemented")
}
func (UnimplementedTwopcServer) IntershardParticipantClientRequest(context.Context, *ClientReq) (*ClientResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IntershardParticipantClientRequest not implemented")
}
func (UnimplementedTwopcServer) PrepareRequest(context.Context, *PrepareReq) (*PromiseAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareRequest not implemented")
}
func (UnimplementedTwopcServer) AcceptRequest(context.Context, *Accept) (*Accepted, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptRequest not implemented")
}
func (UnimplementedTwopcServer) TwoPCAcceptRequest(context.Context, *Accept) (*Accepted, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCAcceptRequest not implemented")
}
func (UnimplementedTwopcServer) Commit(context.Context, *CommitMessage) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedTwopcServer) TwoPCPaxosAbortCommit(context.Context, *CommitMessage) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCPaxosAbortCommit not implemented")
}
func (UnimplementedTwopcServer) NewViewRequest(context.Context, *NewViewReq) (*NewView, error) {
	return nil, status.Error(codes.Unimplemented, "method NewViewRequest not implemented")
}
func (UnimplementedTwopcServer) NewViewUpdate(context.Context, *Ballot) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NewViewUpdate not implemented")
}
func (UnimplementedTwopcServer) UpdateAvailability(context.Context, *IsAvailable) (*IsAvailable, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAvailability not implemented")
}
func (UnimplementedTwopcServer) PrintDB(context.Context, *Empty) (*AllBalance, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedTwopcServer) PrintLogs(context.Context, *Empty) (*AllLogs, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintLogs not implemented")
}
func (UnimplementedTwopcServer) PrintBalance(context.Context, *ClientID) (*Balance, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintBalance not implemented")
}
func (UnimplementedTwopcServer) Flush(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedTwopcServer) GetCurrentLeader(context.Context, *Empty) (*Ballot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentLeader not implemented")
}
func (UnimplementedTwopcServer) TwoPCClientRequest(context.Context, *ClientReq) (*ClientResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCClientRequest not implemented")
}
func (UnimplementedTwopcServer) TwoPCPrepare(context.Context, *TwoPCMessage) (*Prepared, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCPrepare not implemented")
}
func (UnimplementedTwopcServer) TwoPCAbort(context.Context, *TwoPCMessage) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCAbort not implemented")
}
func (UnimplementedTwopcServer) TwoPCCommit(context.Context, *TwoPCMessage) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCCommit not implemented")
}
func (UnimplementedTwopcServer) UpdateClients(context.Context, *TwoPCMessage) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClients not implemented")
}
func (UnimplementedTwopcServer) mustEmbedUnimplementedTwopcServer() {}
func (UnimplementedTwopcServer) testEmbeddedByValue()               {}

// UnsafeTwopcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwopcServer will
// result in compilation errors.
type UnsafeTwopcServer interface {
	mustEmbedUnimplementedTwopcServer()
}

func RegisterTwopcServer(s grpc.ServiceRegistrar, srv TwopcServer) {
	// If the following call panics, it indicates UnimplementedTwopcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Twopc_ServiceDesc, srv)
}

func _Twopc_ClientRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).ClientRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_ClientRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).ClientRequest(ctx, req.(*ClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_ClientReadRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).ClientReadRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_ClientReadRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).ClientReadRequest(ctx, req.(*ClientReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_IntershardParticipantClientRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).IntershardParticipantClientRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_IntershardParticipantClientRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).IntershardParticipantClientRequest(ctx, req.(*ClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_PrepareRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).PrepareRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_PrepareRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).PrepareRequest(ctx, req.(*PrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_AcceptRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accept)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).AcceptRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_AcceptRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).AcceptRequest(ctx, req.(*Accept))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_TwoPCAcceptRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accept)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).TwoPCAcceptRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_TwoPCAcceptRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).TwoPCAcceptRequest(ctx, req.(*Accept))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).Commit(ctx, req.(*CommitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_TwoPCPaxosAbortCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).TwoPCPaxosAbortCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_TwoPCPaxosAbortCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).TwoPCPaxosAbortCommit(ctx, req.(*CommitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_NewViewRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).NewViewRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_NewViewRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).NewViewRequest(ctx, req.(*NewViewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_NewViewUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ballot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).NewViewUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_NewViewUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).NewViewUpdate(ctx, req.(*Ballot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_UpdateAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAvailable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).UpdateAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_UpdateAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).UpdateAvailability(ctx, req.(*IsAvailable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).PrintDB(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_PrintLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).PrintLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_PrintLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).PrintLogs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_PrintBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).PrintBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_PrintBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).PrintBalance(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).Flush(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_GetCurrentLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).GetCurrentLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_GetCurrentLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).GetCurrentLeader(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_TwoPCClientRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).TwoPCClientRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_TwoPCClientRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).TwoPCClientRequest(ctx, req.(*ClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_TwoPCPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).TwoPCPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_TwoPCPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).TwoPCPrepare(ctx, req.(*TwoPCMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_TwoPCAbort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).TwoPCAbort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_TwoPCAbort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).TwoPCAbort(ctx, req.(*TwoPCMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_TwoPCCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).TwoPCCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_TwoPCCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).TwoPCCommit(ctx, req.(*TwoPCMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twopc_UpdateClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwopcServer).UpdateClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Twopc_UpdateClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwopcServer).UpdateClients(ctx, req.(*TwoPCMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Twopc_ServiceDesc is the grpc.ServiceDesc for Twopc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Twopc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "twopc.twopc",
	HandlerType: (*TwopcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientRequest",
			Handler:    _Twopc_ClientRequest_Handler,
		},
		{
			MethodName: "ClientReadRequest",
			Handler:    _Twopc_ClientReadRequest_Handler,
		},
		{
			MethodName: "IntershardParticipantClientRequest",
			Handler:    _Twopc_IntershardParticipantClientRequest_Handler,
		},
		{
			MethodName: "PrepareRequest",
			Handler:    _Twopc_PrepareRequest_Handler,
		},
		{
			MethodName: "AcceptRequest",
			Handler:    _Twopc_AcceptRequest_Handler,
		},
		{
			MethodName: "TwoPCAcceptRequest",
			Handler:    _Twopc_TwoPCAcceptRequest_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Twopc_Commit_Handler,
		},
		{
			MethodName: "TwoPCPaxosAbortCommit",
			Handler:    _Twopc_TwoPCPaxosAbortCommit_Handler,
		},
		{
			MethodName: "NewViewRequest",
			Handler:    _Twopc_NewViewRequest_Handler,
		},
		{
			MethodName: "NewViewUpdate",
			Handler:    _Twopc_NewViewUpdate_Handler,
		},
		{
			MethodName: "UpdateAvailability",
			Handler:    _Twopc_UpdateAvailability_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _Twopc_PrintDB_Handler,
		},
		{
			MethodName: "PrintLogs",
			Handler:    _Twopc_PrintLogs_Handler,
		},
		{
			MethodName: "PrintBalance",
			Handler:    _Twopc_PrintBalance_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _Twopc_Flush_Handler,
		},
		{
			MethodName: "GetCurrentLeader",
			Handler:    _Twopc_GetCurrentLeader_Handler,
		},
		{
			MethodName: "TwoPCClientRequest",
			Handler:    _Twopc_TwoPCClientRequest_Handler,
		},
		{
			MethodName: "TwoPCPrepare",
			Handler:    _Twopc_TwoPCPrepare_Handler,
		},
		{
			MethodName: "TwoPCAbort",
			Handler:    _Twopc_TwoPCAbort_Handler,
		},
		{
			MethodName: "TwoPCCommit",
			Handler:    _Twopc_TwoPCCommit_Handler,
		},
		{
			MethodName: "UpdateClients",
			Handler:    _Twopc_UpdateClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twopc.proto",
}
