// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.17.0
// source: paxos.proto

package paxos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ballot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int32                  `protobuf:"varint,1,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	ProcessID      int32                  `protobuf:"varint,2,opt,name=ProcessID,proto3" json:"ProcessID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	mi := &file_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *Ballot) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Ballot) GetProcessID() int32 {
	if x != nil {
		return x.ProcessID
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Reciever      string                 `protobuf:"bytes,2,opt,name=Reciever,proto3" json:"Reciever,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReciever() string {
	if x != nil {
		return x.Reciever
	}
	return ""
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// (AcceptNum, AcceptSeq, AcceptVal)
type AcceptLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	AcceptSeq     int32                  `protobuf:"varint,2,opt,name=AcceptSeq,proto3" json:"AcceptSeq,omitempty"` //sequence number
	AcceptVal     *ClientReq             `protobuf:"bytes,3,opt,name=AcceptVal,proto3" json:"AcceptVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptLog) Reset() {
	*x = AcceptLog{}
	mi := &file_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptLog) ProtoMessage() {}

func (x *AcceptLog) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptLog.ProtoReflect.Descriptor instead.
func (*AcceptLog) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptLog) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptLog) GetAcceptSeq() int32 {
	if x != nil {
		return x.AcceptSeq
	}
	return 0
}

func (x *AcceptLog) GetAcceptVal() *ClientReq {
	if x != nil {
		return x.AcceptVal
	}
	return nil
}

// ⟨REQUEST,t,τ,c⟩
type ClientReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Client        string                 `protobuf:"bytes,3,opt,name=Client,proto3" json:"Client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReq) Reset() {
	*x = ClientReq{}
	mi := &file_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReq) ProtoMessage() {}

func (x *ClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReq.ProtoReflect.Descriptor instead.
func (*ClientReq) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *ClientReq) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ClientReq) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClientReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

// ⟨REPLY,b,τ,c,r⟩, r=success/failed boolean flag
type ClientResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Client        string                 `protobuf:"bytes,3,opt,name=Client,proto3" json:"Client,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResp) Reset() {
	*x = ClientResp{}
	mi := &file_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResp) ProtoMessage() {}

func (x *ClientResp) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResp.ProtoReflect.Descriptor instead.
func (*ClientResp) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *ClientResp) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *ClientResp) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClientResp) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ClientResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ⟨PREPARE,b⟩
type PrepareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareReq) Reset() {
	*x = PrepareReq{}
	mi := &file_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReq) ProtoMessage() {}

func (x *PrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReq.ProtoReflect.Descriptor instead.
func (*PrepareReq) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareReq) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

// ⟨ACK,b,AcceptLog⟩
type PromiseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	AcceptLog     []string               `protobuf:"bytes,2,rep,name=AcceptLog,proto3" json:"AcceptLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseAck) Reset() {
	*x = PromiseAck{}
	mi := &file_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseAck) ProtoMessage() {}

func (x *PromiseAck) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseAck.ProtoReflect.Descriptor instead.
func (*PromiseAck) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *PromiseAck) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *PromiseAck) GetAcceptLog() []string {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

// ⟨ACCEPT,b,s,m⟩
type Accept struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ballot         *Ballot                `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	ClientReq      *ClientReq             `protobuf:"bytes,3,opt,name=ClientReq,proto3" json:"ClientReq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Accept) Reset() {
	*x = Accept{}
	mi := &file_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accept) ProtoMessage() {}

func (x *Accept) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accept.ProtoReflect.Descriptor instead.
func (*Accept) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *Accept) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Accept) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Accept) GetClientReq() *ClientReq {
	if x != nil {
		return x.ClientReq
	}
	return nil
}

// ⟨ACCEPTED,b,s,m,nb⟩
type Accepted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ballot         *Ballot                `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	ClientReq      *ClientReq             `protobuf:"bytes,3,opt,name=ClientReq,proto3" json:"ClientReq,omitempty"`
	NBallot        int32                  `protobuf:"varint,4,opt,name=NBallot,proto3" json:"NBallot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Accepted) Reset() {
	*x = Accepted{}
	mi := &file_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accepted) ProtoMessage() {}

func (x *Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accepted.ProtoReflect.Descriptor instead.
func (*Accepted) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *Accepted) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Accepted) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Accepted) GetClientReq() *ClientReq {
	if x != nil {
		return x.ClientReq
	}
	return nil
}

func (x *Accepted) GetNBallot() int32 {
	if x != nil {
		return x.NBallot
	}
	return 0
}

// ⟨COMMIT,b,s,m⟩
type CommitMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ballot         *Ballot                `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	ClientReq      *ClientReq             `protobuf:"bytes,3,opt,name=ClientReq,proto3" json:"ClientReq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *CommitMessage) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *CommitMessage) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CommitMessage) GetClientReq() *ClientReq {
	if x != nil {
		return x.ClientReq
	}
	return nil
}

type NewViewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewReq) Reset() {
	*x = NewViewReq{}
	mi := &file_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewReq) ProtoMessage() {}

func (x *NewViewReq) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewReq.ProtoReflect.Descriptor instead.
func (*NewViewReq) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *NewViewReq) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

type NewView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptLog     []string               `protobuf:"bytes,1,rep,name=AcceptLog,proto3" json:"AcceptLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewView) Reset() {
	*x = NewView{}
	mi := &file_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewView) ProtoMessage() {}

func (x *NewView) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewView.ProtoReflect.Descriptor instead.
func (*NewView) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{11}
}

func (x *NewView) GetAcceptLog() []string {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type NewViewUp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int32                  `protobuf:"varint,1,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	AcceptLog      *AcceptLog             `protobuf:"bytes,2,opt,name=AcceptLog,proto3" json:"AcceptLog,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NewViewUp) Reset() {
	*x = NewViewUp{}
	mi := &file_paxos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewUp) ProtoMessage() {}

func (x *NewViewUp) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewUp.ProtoReflect.Descriptor instead.
func (*NewViewUp) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{12}
}

func (x *NewViewUp) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *NewViewUp) GetAcceptLog() *AcceptLog {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type NewViewUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewViewUp     []*NewViewUp           `protobuf:"bytes,1,rep,name=NewViewUp,proto3" json:"NewViewUp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewUpdated) Reset() {
	*x = NewViewUpdated{}
	mi := &file_paxos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewUpdated) ProtoMessage() {}

func (x *NewViewUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewUpdated.ProtoReflect.Descriptor instead.
func (*NewViewUpdated) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{13}
}

func (x *NewViewUpdated) GetNewViewUp() []*NewViewUp {
	if x != nil {
		return x.NewViewUp
	}
	return nil
}

type NewViewResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OK            bool                   `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewResp) Reset() {
	*x = NewViewResp{}
	mi := &file_paxos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewResp) ProtoMessage() {}

func (x *NewViewResp) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewResp.ProtoReflect.Descriptor instead.
func (*NewViewResp) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{14}
}

func (x *NewViewResp) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

type IsAvailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Up            bool                   `protobuf:"varint,1,opt,name=Up,proto3" json:"Up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAvailable) Reset() {
	*x = IsAvailable{}
	mi := &file_paxos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAvailable) ProtoMessage() {}

func (x *IsAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAvailable.ProtoReflect.Descriptor instead.
func (*IsAvailable) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{15}
}

func (x *IsAvailable) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_paxos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{16}
}

func (x *Balance) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type AllBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       []*Balance             `protobuf:"bytes,1,rep,name=Balance,proto3" json:"Balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllBalance) Reset() {
	*x = AllBalance{}
	mi := &file_paxos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllBalance) ProtoMessage() {}

func (x *AllBalance) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllBalance.ProtoReflect.Descriptor instead.
func (*AllBalance) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{17}
}

func (x *AllBalance) GetBalance() []*Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=Log,proto3" json:"Log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_paxos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{18}
}

func (x *Log) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type AllLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           []string               `protobuf:"bytes,1,rep,name=Log,proto3" json:"Log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllLogs) Reset() {
	*x = AllLogs{}
	mi := &file_paxos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLogs) ProtoMessage() {}

func (x *AllLogs) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLogs.ProtoReflect.Descriptor instead.
func (*AllLogs) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{19}
}

func (x *AllLogs) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

type ClientID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientID) Reset() {
	*x = ClientID{}
	mi := &file_paxos_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientID) ProtoMessage() {}

func (x *ClientID) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientID.ProtoReflect.Descriptor instead.
func (*ClientID) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{20}
}

func (x *ClientID) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_paxos_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{21}
}

var File_paxos_proto protoreflect.FileDescriptor

const file_paxos_proto_rawDesc = "" +
	"\n" +
	"\vpaxos.proto\x12\x05paxos\x1a\x1fgoogle/protobuf/Timestamp.proto\"N\n" +
	"\x06Ballot\x12&\n" +
	"\x0eSequenceNumber\x18\x01 \x01(\x05R\x0eSequenceNumber\x12\x1c\n" +
	"\tProcessID\x18\x02 \x01(\x05R\tProcessID\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06Sender\x18\x01 \x01(\tR\x06Sender\x12\x1a\n" +
	"\bReciever\x18\x02 \x01(\tR\bReciever\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x05R\x06Amount\"\x80\x01\n" +
	"\tAcceptLog\x12%\n" +
	"\x06Ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06Ballot\x12\x1c\n" +
	"\tAcceptSeq\x18\x02 \x01(\x05R\tAcceptSeq\x12.\n" +
	"\tAcceptVal\x18\x03 \x01(\v2\x10.paxos.ClientReqR\tAcceptVal\"\x93\x01\n" +
	"\tClientReq\x124\n" +
	"\vTransaction\x18\x01 \x01(\v2\x12.paxos.TransactionR\vTransaction\x128\n" +
	"\tTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x12\x16\n" +
	"\x06Client\x18\x03 \x01(\tR\x06Client\"\x9f\x01\n" +
	"\n" +
	"ClientResp\x12%\n" +
	"\x06Ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06Ballot\x128\n" +
	"\tTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x12\x16\n" +
	"\x06Client\x18\x03 \x01(\tR\x06Client\x12\x18\n" +
	"\aSuccess\x18\x04 \x01(\bR\aSuccess\"3\n" +
	"\n" +
	"PrepareReq\x12%\n" +
	"\x06Ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06Ballot\"Q\n" +
	"\n" +
	"PromiseAck\x12%\n" +
	"\x06Ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06Ballot\x12\x1c\n" +
	"\tAcceptLog\x18\x02 \x03(\tR\tAcceptLog\"\x87\x01\n" +
	"\x06Accept\x12%\n" +
	"\x06Ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06Ballot\x12&\n" +
	"\x0eSequenceNumber\x18\x02 \x01(\x05R\x0eSequenceNumber\x12.\n" +
	"\tClientReq\x18\x03 \x01(\v2\x10.paxos.ClientReqR\tClientReq\"\xa3\x01\n" +
	"\bAccepted\x12%\n" +
	"\x06Ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06Ballot\x12&\n" +
	"\x0eSequenceNumber\x18\x02 \x01(\x05R\x0eSequenceNumber\x12.\n" +
	"\tClientReq\x18\x03 \x01(\v2\x10.paxos.ClientReqR\tClientReq\x12\x18\n" +
	"\aNBallot\x18\x04 \x01(\x05R\aNBallot\"\x8e\x01\n" +
	"\rCommitMessage\x12%\n" +
	"\x06Ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06Ballot\x12&\n" +
	"\x0eSequenceNumber\x18\x02 \x01(\x05R\x0eSequenceNumber\x12.\n" +
	"\tClientReq\x18\x03 \x01(\v2\x10.paxos.ClientReqR\tClientReq\"3\n" +
	"\n" +
	"NewViewReq\x12%\n" +
	"\x06Ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06Ballot\"'\n" +
	"\aNewView\x12\x1c\n" +
	"\tAcceptLog\x18\x01 \x03(\tR\tAcceptLog\"c\n" +
	"\tNewViewUp\x12&\n" +
	"\x0eSequenceNumber\x18\x01 \x01(\x05R\x0eSequenceNumber\x12.\n" +
	"\tAcceptLog\x18\x02 \x01(\v2\x10.paxos.AcceptLogR\tAcceptLog\"@\n" +
	"\x0eNewViewUpdated\x12.\n" +
	"\tNewViewUp\x18\x01 \x03(\v2\x10.paxos.NewViewUpR\tNewViewUp\"\x1d\n" +
	"\vNewViewResp\x12\x0e\n" +
	"\x02OK\x18\x01 \x01(\bR\x02OK\"\x1d\n" +
	"\vIsAvailable\x12\x0e\n" +
	"\x02Up\x18\x01 \x01(\bR\x02Up\"#\n" +
	"\aBalance\x12\x18\n" +
	"\aBalance\x18\x01 \x01(\tR\aBalance\"6\n" +
	"\n" +
	"AllBalance\x12(\n" +
	"\aBalance\x18\x01 \x03(\v2\x0e.paxos.BalanceR\aBalance\"\x17\n" +
	"\x03Log\x12\x10\n" +
	"\x03Log\x18\x01 \x01(\tR\x03Log\"\x1b\n" +
	"\aAllLogs\x12\x10\n" +
	"\x03Log\x18\x01 \x03(\tR\x03Log\"&\n" +
	"\bClientID\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\"\a\n" +
	"\x05Empty2\xdd\x04\n" +
	"\x05Paxos\x126\n" +
	"\rClientRequest\x12\x10.paxos.ClientReq\x1a\x11.paxos.ClientResp\"\x00\x128\n" +
	"\x0ePrepareRequest\x12\x11.paxos.PrepareReq\x1a\x11.paxos.PromiseAck\"\x00\x121\n" +
	"\rAcceptRequest\x12\r.paxos.Accept\x1a\x0f.paxos.Accepted\"\x00\x12.\n" +
	"\x06Commit\x12\x14.paxos.CommitMessage\x1a\f.paxos.Empty\"\x00\x123\n" +
	"\x0eNewViewRequest\x12\x11.paxos.NewViewReq\x1a\x0e.paxos.NewView\x12.\n" +
	"\rNewViewUpdate\x12\r.paxos.Ballot\x1a\f.paxos.Empty\"\x00\x12<\n" +
	"\x12UpdateAvailability\x12\x12.paxos.IsAvailable\x1a\x12.paxos.IsAvailable\x12*\n" +
	"\aPrintDB\x12\f.paxos.Empty\x1a\x11.paxos.AllBalance\x12)\n" +
	"\tPrintLogs\x12\f.paxos.Empty\x1a\x0e.paxos.AllLogs\x12/\n" +
	"\fPrintBalance\x12\x0f.paxos.ClientID\x1a\x0e.paxos.Balance\x12#\n" +
	"\x05Flush\x12\f.paxos.Empty\x1a\f.paxos.Empty\x12/\n" +
	"\x10GetCurrentLeader\x12\f.paxos.Empty\x1a\r.paxos.BallotB\bZ\x06/paxosb\x06proto3"

var (
	file_paxos_proto_rawDescOnce sync.Once
	file_paxos_proto_rawDescData []byte
)

func file_paxos_proto_rawDescGZIP() []byte {
	file_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)))
	})
	return file_paxos_proto_rawDescData
}

var file_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_paxos_proto_goTypes = []any{
	(*Ballot)(nil),                // 0: paxos.Ballot
	(*Transaction)(nil),           // 1: paxos.Transaction
	(*AcceptLog)(nil),             // 2: paxos.AcceptLog
	(*ClientReq)(nil),             // 3: paxos.ClientReq
	(*ClientResp)(nil),            // 4: paxos.ClientResp
	(*PrepareReq)(nil),            // 5: paxos.PrepareReq
	(*PromiseAck)(nil),            // 6: paxos.PromiseAck
	(*Accept)(nil),                // 7: paxos.Accept
	(*Accepted)(nil),              // 8: paxos.Accepted
	(*CommitMessage)(nil),         // 9: paxos.CommitMessage
	(*NewViewReq)(nil),            // 10: paxos.NewViewReq
	(*NewView)(nil),               // 11: paxos.NewView
	(*NewViewUp)(nil),             // 12: paxos.NewViewUp
	(*NewViewUpdated)(nil),        // 13: paxos.NewViewUpdated
	(*NewViewResp)(nil),           // 14: paxos.NewViewResp
	(*IsAvailable)(nil),           // 15: paxos.IsAvailable
	(*Balance)(nil),               // 16: paxos.Balance
	(*AllBalance)(nil),            // 17: paxos.AllBalance
	(*Log)(nil),                   // 18: paxos.Log
	(*AllLogs)(nil),               // 19: paxos.AllLogs
	(*ClientID)(nil),              // 20: paxos.ClientID
	(*Empty)(nil),                 // 21: paxos.Empty
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_paxos_proto_depIdxs = []int32{
	0,  // 0: paxos.AcceptLog.Ballot:type_name -> paxos.Ballot
	3,  // 1: paxos.AcceptLog.AcceptVal:type_name -> paxos.ClientReq
	1,  // 2: paxos.ClientReq.Transaction:type_name -> paxos.Transaction
	22, // 3: paxos.ClientReq.Timestamp:type_name -> google.protobuf.Timestamp
	0,  // 4: paxos.ClientResp.Ballot:type_name -> paxos.Ballot
	22, // 5: paxos.ClientResp.Timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: paxos.PrepareReq.Ballot:type_name -> paxos.Ballot
	0,  // 7: paxos.PromiseAck.Ballot:type_name -> paxos.Ballot
	0,  // 8: paxos.Accept.Ballot:type_name -> paxos.Ballot
	3,  // 9: paxos.Accept.ClientReq:type_name -> paxos.ClientReq
	0,  // 10: paxos.Accepted.Ballot:type_name -> paxos.Ballot
	3,  // 11: paxos.Accepted.ClientReq:type_name -> paxos.ClientReq
	0,  // 12: paxos.CommitMessage.Ballot:type_name -> paxos.Ballot
	3,  // 13: paxos.CommitMessage.ClientReq:type_name -> paxos.ClientReq
	0,  // 14: paxos.NewViewReq.Ballot:type_name -> paxos.Ballot
	2,  // 15: paxos.NewViewUp.AcceptLog:type_name -> paxos.AcceptLog
	12, // 16: paxos.NewViewUpdated.NewViewUp:type_name -> paxos.NewViewUp
	16, // 17: paxos.AllBalance.Balance:type_name -> paxos.Balance
	3,  // 18: paxos.Paxos.ClientRequest:input_type -> paxos.ClientReq
	5,  // 19: paxos.Paxos.PrepareRequest:input_type -> paxos.PrepareReq
	7,  // 20: paxos.Paxos.AcceptRequest:input_type -> paxos.Accept
	9,  // 21: paxos.Paxos.Commit:input_type -> paxos.CommitMessage
	10, // 22: paxos.Paxos.NewViewRequest:input_type -> paxos.NewViewReq
	0,  // 23: paxos.Paxos.NewViewUpdate:input_type -> paxos.Ballot
	15, // 24: paxos.Paxos.UpdateAvailability:input_type -> paxos.IsAvailable
	21, // 25: paxos.Paxos.PrintDB:input_type -> paxos.Empty
	21, // 26: paxos.Paxos.PrintLogs:input_type -> paxos.Empty
	20, // 27: paxos.Paxos.PrintBalance:input_type -> paxos.ClientID
	21, // 28: paxos.Paxos.Flush:input_type -> paxos.Empty
	21, // 29: paxos.Paxos.GetCurrentLeader:input_type -> paxos.Empty
	4,  // 30: paxos.Paxos.ClientRequest:output_type -> paxos.ClientResp
	6,  // 31: paxos.Paxos.PrepareRequest:output_type -> paxos.PromiseAck
	8,  // 32: paxos.Paxos.AcceptRequest:output_type -> paxos.Accepted
	21, // 33: paxos.Paxos.Commit:output_type -> paxos.Empty
	11, // 34: paxos.Paxos.NewViewRequest:output_type -> paxos.NewView
	21, // 35: paxos.Paxos.NewViewUpdate:output_type -> paxos.Empty
	15, // 36: paxos.Paxos.UpdateAvailability:output_type -> paxos.IsAvailable
	17, // 37: paxos.Paxos.PrintDB:output_type -> paxos.AllBalance
	19, // 38: paxos.Paxos.PrintLogs:output_type -> paxos.AllLogs
	16, // 39: paxos.Paxos.PrintBalance:output_type -> paxos.Balance
	21, // 40: paxos.Paxos.Flush:output_type -> paxos.Empty
	0,  // 41: paxos.Paxos.GetCurrentLeader:output_type -> paxos.Ballot
	30, // [30:42] is the sub-list for method output_type
	18, // [18:30] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_paxos_proto_init() }
func file_paxos_proto_init() {
	if File_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_proto_msgTypes,
	}.Build()
	File_paxos_proto = out.File
	file_paxos_proto_goTypes = nil
	file_paxos_proto_depIdxs = nil
}
