// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.17.0
// source: paxos.proto

package paxos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paxos_ClientRequest_FullMethodName      = "/paxos.Paxos/ClientRequest"
	Paxos_PrepareRequest_FullMethodName     = "/paxos.Paxos/PrepareRequest"
	Paxos_AcceptRequest_FullMethodName      = "/paxos.Paxos/AcceptRequest"
	Paxos_Commit_FullMethodName             = "/paxos.Paxos/Commit"
	Paxos_NewViewRequest_FullMethodName     = "/paxos.Paxos/NewViewRequest"
	Paxos_NewViewUpdate_FullMethodName      = "/paxos.Paxos/NewViewUpdate"
	Paxos_UpdateAvailability_FullMethodName = "/paxos.Paxos/UpdateAvailability"
	Paxos_PrintDB_FullMethodName            = "/paxos.Paxos/PrintDB"
	Paxos_PrintLogs_FullMethodName          = "/paxos.Paxos/PrintLogs"
	Paxos_PrintBalance_FullMethodName       = "/paxos.Paxos/PrintBalance"
	Paxos_Flush_FullMethodName              = "/paxos.Paxos/Flush"
	Paxos_GetCurrentLeader_FullMethodName   = "/paxos.Paxos/GetCurrentLeader"
)

// PaxosClient is the client API for Paxos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaxosClient interface {
	ClientRequest(ctx context.Context, in *ClientReq, opts ...grpc.CallOption) (*ClientResp, error)
	PrepareRequest(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PromiseAck, error)
	AcceptRequest(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*Accepted, error)
	Commit(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*Empty, error)
	NewViewRequest(ctx context.Context, in *NewViewReq, opts ...grpc.CallOption) (*NewView, error)
	NewViewUpdate(ctx context.Context, in *Ballot, opts ...grpc.CallOption) (*Empty, error)
	UpdateAvailability(ctx context.Context, in *IsAvailable, opts ...grpc.CallOption) (*IsAvailable, error)
	PrintDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllBalance, error)
	PrintLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllLogs, error)
	PrintBalance(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*Balance, error)
	Flush(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetCurrentLeader(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ballot, error)
}

type paxosClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosClient(cc grpc.ClientConnInterface) PaxosClient {
	return &paxosClient{cc}
}

func (c *paxosClient) ClientRequest(ctx context.Context, in *ClientReq, opts ...grpc.CallOption) (*ClientResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResp)
	err := c.cc.Invoke(ctx, Paxos_ClientRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) PrepareRequest(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PromiseAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromiseAck)
	err := c.cc.Invoke(ctx, Paxos_PrepareRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) AcceptRequest(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*Accepted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Accepted)
	err := c.cc.Invoke(ctx, Paxos_AcceptRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) Commit(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Paxos_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) NewViewRequest(ctx context.Context, in *NewViewReq, opts ...grpc.CallOption) (*NewView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewView)
	err := c.cc.Invoke(ctx, Paxos_NewViewRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) NewViewUpdate(ctx context.Context, in *Ballot, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Paxos_NewViewUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) UpdateAvailability(ctx context.Context, in *IsAvailable, opts ...grpc.CallOption) (*IsAvailable, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAvailable)
	err := c.cc.Invoke(ctx, Paxos_UpdateAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) PrintDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllBalance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllBalance)
	err := c.cc.Invoke(ctx, Paxos_PrintDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) PrintLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllLogs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllLogs)
	err := c.cc.Invoke(ctx, Paxos_PrintLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) PrintBalance(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*Balance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Balance)
	err := c.cc.Invoke(ctx, Paxos_PrintBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) Flush(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Paxos_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) GetCurrentLeader(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ballot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ballot)
	err := c.cc.Invoke(ctx, Paxos_GetCurrentLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosServer is the server API for Paxos service.
// All implementations must embed UnimplementedPaxosServer
// for forward compatibility.
type PaxosServer interface {
	ClientRequest(context.Context, *ClientReq) (*ClientResp, error)
	PrepareRequest(context.Context, *PrepareReq) (*PromiseAck, error)
	AcceptRequest(context.Context, *Accept) (*Accepted, error)
	Commit(context.Context, *CommitMessage) (*Empty, error)
	NewViewRequest(context.Context, *NewViewReq) (*NewView, error)
	NewViewUpdate(context.Context, *Ballot) (*Empty, error)
	UpdateAvailability(context.Context, *IsAvailable) (*IsAvailable, error)
	PrintDB(context.Context, *Empty) (*AllBalance, error)
	PrintLogs(context.Context, *Empty) (*AllLogs, error)
	PrintBalance(context.Context, *ClientID) (*Balance, error)
	Flush(context.Context, *Empty) (*Empty, error)
	GetCurrentLeader(context.Context, *Empty) (*Ballot, error)
	mustEmbedUnimplementedPaxosServer()
}

// UnimplementedPaxosServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaxosServer struct{}

func (UnimplementedPaxosServer) ClientRequest(context.Context, *ClientReq) (*ClientResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientRequest not implemented")
}
func (UnimplementedPaxosServer) PrepareRequest(context.Context, *PrepareReq) (*PromiseAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareRequest not implemented")
}
func (UnimplementedPaxosServer) AcceptRequest(context.Context, *Accept) (*Accepted, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptRequest not implemented")
}
func (UnimplementedPaxosServer) Commit(context.Context, *CommitMessage) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPaxosServer) NewViewRequest(context.Context, *NewViewReq) (*NewView, error) {
	return nil, status.Error(codes.Unimplemented, "method NewViewRequest not implemented")
}
func (UnimplementedPaxosServer) NewViewUpdate(context.Context, *Ballot) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NewViewUpdate not implemented")
}
func (UnimplementedPaxosServer) UpdateAvailability(context.Context, *IsAvailable) (*IsAvailable, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAvailability not implemented")
}
func (UnimplementedPaxosServer) PrintDB(context.Context, *Empty) (*AllBalance, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedPaxosServer) PrintLogs(context.Context, *Empty) (*AllLogs, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintLogs not implemented")
}
func (UnimplementedPaxosServer) PrintBalance(context.Context, *ClientID) (*Balance, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintBalance not implemented")
}
func (UnimplementedPaxosServer) Flush(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedPaxosServer) GetCurrentLeader(context.Context, *Empty) (*Ballot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentLeader not implemented")
}
func (UnimplementedPaxosServer) mustEmbedUnimplementedPaxosServer() {}
func (UnimplementedPaxosServer) testEmbeddedByValue()               {}

// UnsafePaxosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosServer will
// result in compilation errors.
type UnsafePaxosServer interface {
	mustEmbedUnimplementedPaxosServer()
}

func RegisterPaxosServer(s grpc.ServiceRegistrar, srv PaxosServer) {
	// If the following call panics, it indicates UnimplementedPaxosServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paxos_ServiceDesc, srv)
}

func _Paxos_ClientRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).ClientRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_ClientRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).ClientRequest(ctx, req.(*ClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_PrepareRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).PrepareRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_PrepareRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).PrepareRequest(ctx, req.(*PrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_AcceptRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accept)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).AcceptRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_AcceptRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).AcceptRequest(ctx, req.(*Accept))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Commit(ctx, req.(*CommitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_NewViewRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).NewViewRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_NewViewRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).NewViewRequest(ctx, req.(*NewViewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_NewViewUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ballot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).NewViewUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_NewViewUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).NewViewUpdate(ctx, req.(*Ballot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_UpdateAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAvailable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).UpdateAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_UpdateAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).UpdateAvailability(ctx, req.(*IsAvailable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).PrintDB(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_PrintLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).PrintLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_PrintLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).PrintLogs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_PrintBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).PrintBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_PrintBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).PrintBalance(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Flush(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_GetCurrentLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).GetCurrentLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_GetCurrentLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).GetCurrentLeader(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Paxos_ServiceDesc is the grpc.ServiceDesc for Paxos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paxos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.Paxos",
	HandlerType: (*PaxosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientRequest",
			Handler:    _Paxos_ClientRequest_Handler,
		},
		{
			MethodName: "PrepareRequest",
			Handler:    _Paxos_PrepareRequest_Handler,
		},
		{
			MethodName: "AcceptRequest",
			Handler:    _Paxos_AcceptRequest_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Paxos_Commit_Handler,
		},
		{
			MethodName: "NewViewRequest",
			Handler:    _Paxos_NewViewRequest_Handler,
		},
		{
			MethodName: "NewViewUpdate",
			Handler:    _Paxos_NewViewUpdate_Handler,
		},
		{
			MethodName: "UpdateAvailability",
			Handler:    _Paxos_UpdateAvailability_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _Paxos_PrintDB_Handler,
		},
		{
			MethodName: "PrintLogs",
			Handler:    _Paxos_PrintLogs_Handler,
		},
		{
			MethodName: "PrintBalance",
			Handler:    _Paxos_PrintBalance_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _Paxos_Flush_Handler,
		},
		{
			MethodName: "GetCurrentLeader",
			Handler:    _Paxos_GetCurrentLeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}
